# Dependency Review Action
#
# This Action will scan dependency manifest files that change as part of a Pull Request,
# surfacing known-vulnerable versions of the packages declared or updated in the PR.
# Once installed, if the workflow run is marked as required,
# PRs introducing known-vulnerable packages will be blocked from merging.
#
# Source repository: https://github.com/actions/dependency-review-action
# This GitHub Actions workflow is named 'Dependency Review'.
# It is triggered by pull requests.
#
# Permissions:
# - The workflow has read access to the repository contents.
#
# Jobs:
# - dependency-review:
#   - Runs on the latest Ubuntu runner.
#   - Steps:
#     1. Harden Runner:
#        - Uses the 'step-security/harden-runner' action (version v2.10.4).
#        - Configured with an egress policy set to audit.
#     2. Checkout Repository:
#        - Uses the 'actions/checkout' action (version v4.2.2) to check out the repository.
#     3. Dependency Review:
#        - Uses the 'actions/dependency-review-action' (version v4.5.0) to perform a dependency review.

name: "Dependency Review"
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:


permissions:
  contents: read

concurrency:
  group: dependency-review-${{ github.ref }}
  cancel-in-progress: false

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit

      - name: "Checkout Repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: "Dependency Review"
        uses: actions/dependency-review-action@3c4e3dcb1aa7874d2c16be7d79418e9b7efd6261 # v4.8.2
